### ISSUE TITLE
Reference IpfsCore as a submodule

### ISSUE THREAD

**Issue by erikmav** [ipfs-shipyard/net-ipfs-http-client#23]
As a smaller version of the work attempted for https://github.com/ipfs-shipyard/net-ipfs-core/issues/16 instead of pulling in all of the C# repos to one place, just combine this repo and net-ipfs-core into a single repo. This repo's code and Core need to almost always be in sync, and we need to either combine or add Core as a submodule in this repo to make it easier to develop across both.

Also use central package versioning in the combined repo to avoid having to maintain dependent package lists in 4 csproj files.

**Comment by Arlodotexe** [comment]
That said, unlike the `net-ipfs-core` library, we aren't closing this off yet.

It's a very good point that we could just use a submodule. Tooling on submodules has come a long way in recent years, it would make development _much_ easier.

Let's consider the implications before moving forward, though. What kind of problems could we run into if we did this? Or, are there any good reasons to keep using the nuget package over the submodule?

My time is short today, so I'll come back to this later. Things to think about.

**Comment by Arlodotexe** [comment]
We have CI in both repos, the effort needed to update the NuGet package is negligible. Avoiding submodules means we must use a published version of the NuGet for `net-ipfs-core`, which we should expect as a requirement since end-users of `net-ipfs-http-client` will be pulling in the version of `net-ipfs-core` that we specify.
